### ISSUE TITLE
MATLAB 2016a, vl_compilenn problem

### ISSUE THREAD

**Issue by VincentGu11** [ignaciorlando/red-lesion-detection#1]
Hi ignaciorlando,

I'm trying to segment MA and HE from fundus images like you do. I've tried lots of method however the result is not good enough. I've read your paper "Learning to Detect Red Lesions in Fundus Photographs: An Ensemble Approach based on Deep Learning". I think it's a good way to build ensemble method to solve this problem. 

However, my MATLAB version is MATLAB 2016a, as you said it has a vl_compilenn problem. Could you tell me how to solve this problem？My email address is gushuo1992@gmail.com. Thank you very much!

**Comment by ignaciorlando** [comment]
Hi @VincentGu11,

Good to know that you found interesting our idea.

I didn't manage to compile the file in MATLAB R2016b, but as far as I remember I didn't have any troubles with the earlier versions. What's exactly the error that you're getting so far?

BTW, did you try looking for the error message in the Matconvnet github page? I found that lots of people had issues to compile the library under different architectures and operating systems. If In which platform are you working on? Maybe I can send you the compiled binaries if you want. For sure is not the optimal solution, but at least you will be able to start working with the code a little bit faster.

Don't hesitate in contact me if you have any further question about the code.

**Comment by ignaciorlando** [comment]
Hi @VincentGu11,

Did you try the options I mentioned? Can I help you with something else?
