### ISSUE TITLE
can't get the expected results

### ISSUE THREAD

**Issue by ai1361720220000** [ignaciorlando/red-lesion-detection#12]
Hello!
I'm interested in your work, and i run the project following your notes with DIARETDB1 dataset.
But the results(segment) is not good, most of the candidates are divided into non-objectes....
I am confused whether my CNN results or classify is wrong. But the parameters are all the same with your paper(and the same in your code), can you help me? 
Thank you very much!

**Comment by ignaciorlando** [comment]
Hi! Thanks for your interest in our paper. Could you please elaborate the issue a little bit more? Did you compare the outputs with the results that we have shared online? Did you use the precomputed models that are also provided in our website? I'm on holidays now but I'll come back to this asap.

**Comment by ai1361720220000** [comment]
Hello! Your model is trained with both the HE and MA groundtruth? I combine HE and MA groundtruth together and run the code, the results is expected....

**Comment by ignaciorlando** [comment]
Hi! Yes, exactly. As in the paper by Lama Seoud, we decided to go for simultaneous MA and HE detection (red lesions) to overcome the issue that some labels in the ground truth are wrong (MAs labeled as HEs and viceversa). Good to hear that the problem is solved! :)
