### ISSUE TITLE
About random forest results

### ISSUE THREAD

**Issue by ai1361720220000** [ignaciorlando/red-lesion-detection#13]
Hello!
The classRF_predict_probabilities function returns two value: scores and y_hat. And scores is related to the whole trees' results of probability( 0~1), but what the y_hat means? and how it is calculated. I really confused it , could you help me  ? 
Thank you very much!

**Comment by ignaciorlando** [comment]
Hi! y_hat is the predicted class. It is calculated by taking the maximum probability among classes. For red lesion detection, y_hat will be 0 (not lesion) or 1 (lesion).

**Comment by ai1361720220000** [comment]
I have solved this problem, Thank you orlando, also i wonder how you draw the t-SNE map. Can you share the code? I have tried the MATLAB toolbox, but the results is not as beautiful as yours and less than satisfactory .
Thank you very much!!

**Comment by ignaciorlando** [comment]
Hi! Sure, you can use the script ```script_tsne_representation.m``` to produce that figure! It is in ```RedLesionDetection/scripts/script_tsne_representation.m```. You will need to modify the ```config_tsne_representation.m``` script first to point out to the correct folders. Good luck!

**Comment by ai1361720220000** [comment]
My pc has 16GB RAM, and the matlab pops an error that the array is too huge to deal with.......

**Comment by ignaciorlando** [comment]
Sorry but I cannot help you with it. Try by reducing the number of samples that you want to plot, for instance. Good luck!

**Comment by ai1361720220000** [comment]
OK, thank your for your patience!! nice of you!!
