### ISSUE TITLE
How to extract hemorrhages candidates?

### ISSUE THREAD

**Issue by qwertyDvo** [ignaciorlando/red-lesion-detection#14]
Hello,
Thank you for sharing this project.
Could you please tell me how to find hemorrhages candidates? I found MA candidates but I need hemorrhages candidates.
Thank you in advanced

**Comment by ignaciorlando** [comment]
Hi @qwertyDvo!
As you can see in our paper, our method do not detect MA or HE separately but red lesions in general. The candidate detection algorithm is able to detect the small red lesions in the images without discriminating between each specific type.
Let me know if you need further assistance!
