### ISSUE TITLE
ROC xml file

### ISSUE THREAD

**Issue by qwertyDvo** [ignaciorlando/red-lesion-detection#16]
Hello,
Thank you for this project.
However, I have question about ROC microaneurysm (MA) dataset, the microaneurysm coordinates that determined in xml file do not show any clear MA. Did you notice the same problem? how did you solve it?

Thank you

**Comment by ignaciorlando** [comment]
Hi @qwertyDvo,
Indeed, I have seen that before. The ROC data set seems to have wrong annotations. The only solution I found was to avoid using the data set. I remember that there is a paper complaining about these mistakes, but I cannot find it now.
Hope it helps!

**Comment by qwertyDvo** [comment]
Ok thank you
