### ISSUE TITLE
What are: L, L0, px, K?

### ISSUE THREAD

**Issue by qwertyDvo** [ignaciorlando/red-lesion-detection#17]
Hello all,
I have another question about L, L0, px, K parameters in candidates extraction configuration. What they refer to?

Thank you very much

**Comment by ignaciorlando** [comment]
Hi @qwertyDvo. You can find the details about each parameter on our paper: https://arxiv.org/pdf/1706.03008.pdf.

**Comment by qwertyDvo** [comment]
Thanx for your response. I have another question: you said that your candidates extraction method focus on small red lesion which is MAs. However, I saw in the paper you also highlighted HMs as false negative in figure 10. Could you please explain if also the method extract HMs? does it fail to extract large HMs candidates?
