### ISSUE TITLE
An input is not a numeric array (or GPU support not compiled).

### ISSUE THREAD

**Issue by rockywind** [ignaciorlando/red-lesion-detection#4]
HI,
My current configuration is:
CUDA 8.0
Ubuntu16.04
Matlab2016b
GPU:GTX1080

While running 'RedLesionDetection/scripts/script_train_cnn.m' in GPU mode I get the error:
`train: epoch 01:   1/232:Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 306)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

Error in cnn_red_lesions_train>process_epoch (line 424)
        res = vl_simplenn(net, im, dzdy, res, ...

Error in cnn_red_lesions_train (line 150)
    [net,stats.train(epoch),prof] = process_epoch(net, state, opts, 'train') ;

Error in cnn_red_lesion_detection>train_cnn_from_scratch (line 93)
    [net, info] = cnn_red_lesions_train(net, imdb, getBatch(opts), ...

Error in cnn_red_lesion_detection (line 26)
    [net, info] = train_cnn_from_scratch(opts) ;

Error in script_train_cnn (line 12)
[detector.net, info] = cnn_red_lesion_detection( ...`
Thanks in advance!

**Comment by ignaciorlando** [comment]
Hi!

Did you try by recompiling the MEX files in Matconvnet. You can do that by running:
`vl_compilenn('EnableGpu',true);`

Let me know if you solve the problem with that!

**Comment by rockywind** [comment]
@ignaciorlando Thank you very much! 
I solved it following your advice,but I find another error that  the GPU memory consumes a liitle,when I run the command "watch nviida-smi" training the  model.

**Comment by ignaciorlando** [comment]
That is basically because the training set is not too big and the batch size is not too big either. In any case, the whole training process should not take more than half an hour on GPU.

**Comment by vickykhan89** [comment]
@ignaciorlando I followed your suggestions running the command vl_compilenn('EnableGpu',true);
but i got Could not find a valid NVCC executable\n.
Any suggestions to me please
