### ISSUE TITLE
Error using griddedInterpolant The grid vectors must contain unique points.

### ISSUE THREAD

**Issue by rockywind** [ignaciorlando/red-lesion-detection#5]
Hi!
When I run the script:scipt_segment_red_lesions.m,I get the error:

`Segmenting MA from image 1/1
Computing FROC curve
.
Error using griddedInterpolant
The grid vectors must contain unique points.

Error in interp1 (line 161)
        F = griddedInterpolant(X,V,method);

Error in froc (line 86)
        reference_se_vals = interp1(u_sorted_fpi, u_sorted_per_lesion_sensitivity, fpi_references, 'spline') ;

Error in script_segment_red_lesions (line 100)
    [fpi, per_lesion_sensitivity, froc_score, reference_se_vals, thresholds] = froc(score_maps, gt_labels, true);`

I debug the code,when it run to the script:froc.m in 86 line: reference_se_vals = interp1(u_sorted_fpi, u_sorted_per_lesion_sensitivity, fpi_references, 'spline') ;,the error occurs.

**Comment by ignaciorlando** [comment]
Could you solve this issue? If that's the case, let me know how and I will push the corresponding solution ☺
